# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa7c07eab52c8da54d4fedd7dcac73e195b81eb043487f51aa12a65520da7e592e251860982302ce662f7a8206430a57e67e7cfdef3f0f27e841d729be52de7b

test:
  secret_key_base: 719bfe84ba4734ca9dcee31bf766d48e66ec333fbda6982338e4c6d92f0377106889872f37ec27b3106216b150c2f779ea881546ba34dd28bb068d5ebce3157e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
